"""empty message

Revision ID: 339d6fb23393
Revises: c8b37cf11950
Create Date: 2022-07-20 23:00:53.062428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339d6fb23393'
down_revision = 'c8b37cf11950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('rq_id', sa.String(length=100), nullable=True))
    op.drop_column('video', 'webm_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('webm_url', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('video', 'rq_id')
    # ### end Alembic commands ###
