"""empty message

Revision ID: 3c461bd21055
Revises: 339d6fb23393
Create Date: 2022-07-21 00:38:41.793145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c461bd21055'
down_revision = '339d6fb23393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thumbnail_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'thumbnail_url')
    # ### end Alembic commands ###
