"""empty message

Revision ID: c8b37cf11950
Revises: 83275a74e88f
Create Date: 2022-07-20 15:25:22.694671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b37cf11950'
down_revision = '83275a74e88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('mp4_url', sa.String(length=100), nullable=True))
    op.add_column('video', sa.Column('webm_url', sa.String(length=100), nullable=True))
    op.drop_column('video', 'source_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('source_url', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('video', 'webm_url')
    op.drop_column('video', 'mp4_url')
    # ### end Alembic commands ###
